  name: Pull Request
  on:
    push:

  jobs:
    monorepo:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Monorepo controller
          id: controller
          uses: cloudposse/github-action-monorepo-random-controller@0.1.1
          with:
            dir: ./

      outputs:
        applications: ${{ steps.controller.outputs.apps }}
        changes: ${{ steps.controller.outputs.changes }}
        no-changes: ${{ steps.controller.outputs.no-changes }}

    ci:
      runs-on: ubuntu-latest
      needs: [monorepo]
      # if: ${{ needs.monorepo.outputs.applications != '[]'  }}
      strategy:
        matrix:
          application: ${{ fromJson(needs.monorepo.outputs.applications) }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - run:
            echo "${{ matrix.application }}"
            echo "${{ fromJson(needs.monorepo.outputs) }}"
